pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-west-1'
        ECR_REPOSITORY = '804837308178.dkr.ecr.eu-west-1.amazonaws.com/user-frontend'
        IMAGE_TAG = "${BUILD_NUMBER}"
        NEXT_PUBLIC_API_URL = 'http://YOUR_BACKEND_URL:5000/api'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-user-registration',
                    url: 'https://github.com/shivasaini-devhub/User_Registration.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('frontend') {
                    sh 'npm test'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                        --build-arg NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}" \
                        -t ${ECR_REPOSITORY}:${IMAGE_TAG} \
                        ./frontend
                '''
            }
        }

        stage('AWS ECR Login') {
            steps {
                withAWS(
                    credentials: 'aws-ecr',
                    region: "${AWS_REGION}"
                ) {
                    sh '''
                        aws ecr get-login-password \
                            --region ${AWS_REGION} | \
                        docker login \
                            --username AWS \
                            --password-stdin \
                            804837308178.dkr.ecr.eu-west-1.amazonaws.com
                    '''
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh '''
                    docker push ${ECR_REPOSITORY}:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        success {
            echo "Frontend image pushed successfully: ${ECR_REPOSITORY}:${IMAGE_TAG}"
        }

        failure {
            echo 'Frontend pipeline failed.'
        }

        always {
            cleanWs()
        }
    }
}
